alias e="subl"
alias e.="subl ."
alias s="npm start"
alias k="npm run karma"
alias t="npm test"
alias b="npm run build"
alias dp="npm run deploy"
alias p="~ && cd projects"
alias c="~ && cd contracting"
alias dr="~ && cd projects/dota-recipe"
alias pjr="~ && cd projects/projecter"
alias tt="~ && cd projects/tomato-tracker"
alias fp="~ && cd projects/fightpick-api"
alias zsh='~ && subl .zshrc'
alias za='~ && cd .oh-my-zsh/custom && subl alias.zsh'
alias pt='~ && cd contracting/prime/prime-tenancy'
alias pts='pt && npm run dev'
alias mt='sudo mount -a'
alias major='gco master && git pull && npm run release-major'
alias minor='gco master && git pull && npm run release-minor'
alias ptch='gco master && git pull && npm run release-patch'
alias rdel='git ls-files --deleted -z | xargs -0 git rm'
alias ca='ga . && npm run commit'
alias undo='git reset --soft HEAD~'
alias n='sudo -E env "PATH=$PATH" n'